### ISSUE TITLE
CSS Renamer is screwed up

### ISSUE THREAD

**Issue by Drflash55** [megamit/repository#12]
Because of Discord Canary having a new update that changes some of the CSS, you're getting this when you try to rename someone, or adding a tag.
![image](https://user-images.githubusercontent.com/13694448/27506406-d4c27974-5884-11e7-92f9-d60e963da42b.png)

This can easily be fixed if the CSS for Renamer is set to match the new look, as shown below.
![image](https://user-images.githubusercontent.com/13694448/27506408-edfb49fc-5884-11e7-9540-85c2724428e0.png)

**Comment by megamit** [comment]
Should be usable now
