### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by Drflash55** [megamit/repository#20]
Discord has updated a lot since you last updated your plugin, and I was wondering if you were still working on this from 3 months ago.

I liked using your plugin and I do hope you bring it back some day, since most of the updates have now broken your plugin entirely.

**Comment by ShayBox** [comment]
You need to specify which plugin, renamer still works. and search is unneeded as discord has its own.

**Comment by megamit** [comment]
Been a tad burnt out with discord plugins not finding it very fun. Ill maintain my plugins as long as no one makes a better one. Please specify what plugins you are having issues with and I'll try to take a look

**Comment by Drflash55** [comment]
I'm using Renamer.

There's no option in the context menu to rename people in the member list.
![image](https://user-images.githubusercontent.com/13694448/30775745-ef2dd3f0-a067-11e7-8326-af5de29cee81.png)

I'm using V1.5.1.
![image](https://user-images.githubusercontent.com/13694448/30775740-cb018f1c-a067-11e7-8362-773811d00f7e.png)

**Comment by Drflash55** [comment]
Obtained V1.5.2, context menu now shows those two options.
![image](https://user-images.githubusercontent.com/13694448/30776803-0f54e94e-a07b-11e7-8fae-d2014e43e61f.png)


Thanks again, man!
