### ISSUE TITLE
Renamer 1.5.3 causing infinload

### ISSUE THREAD

**Issue by nihaals** [megamit/repository#27]
Latest PTB. I used a version from a Pull Request, but I believe I updated to the pushed latest (1.5.3) which is now causing infinite loading (Which is strange as that's a bug with the new react version, which was fixed in 1.5.3)

**Comment by Krotain** [comment]
Also experiencing this

**Comment by JWWolstenholme** [comment]
> Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
>     at Renamer.attachChatListners (<anonymous>:672:15)
>     at Renamer.start (<anonymous>:500:10)
>     at Object.<anonymous> (main.min.js:128)
>     at Function.each (jquery.min.js:4)
>     at PluginModule.loadPlugins (main.min.js:127)
>     at gwDefer (main.min.js:4)
>     at r (d50ec5b….js:79)

Also have this problem. That's what the console is complaining about.

**Comment by romashko** [comment]
Fixed in my pullrequest, check it out, dunno when megamit is going to merge it.
