### ISSUE TITLE
Remove custom "bot" tags from BetterDiscord server

### ISSUE THREAD

**Issue by simoniz0r** [megamit/repository#9]
I have the names on my theme set to align to the right side of the screen along with bot tags, but the bot tags from this plugin do not follow the css that I have for regular bot tags.

**Comment by megamit** [comment]
I have no idea what you are talking about. Please provide some screenshots

**Comment by simoniz0r** [comment]
![tags screenshot](http://i.imgur.com/Tjli9vH.png)

**Comment by simoniz0r** [comment]
No?  Could you at least post which sections of your plugin are responsible for this so I can remove them myself?

**Comment by simoniz0r** [comment]
I tried removing their tags in Discord, but a small block ~ 1 or 2 pixels big remains with the color you've chosen for the tag.  I cannot set the color to null like I can with username colors.  I tried removing the tags set to the BetterDiscord devs and such from the config file completely, but that had no effect.

There is actually a bug associated with this in case you don't actually want to make this feature optional...  Removing tags doesn't work properly.  I can remove the text, but not the color.  After removing the text, a small block about 1 or 2 pixels wide remains in the color that was chosen.  There is no option to remove colors like there is with usernames.

**Comment by simoniz0r** [comment]
Someone on the BetterDiscord helped me figure this out.  Apparently there's a delete tag button that I was missing.  It honestly would have been nice to know that this feature even existed when installing this plugin.  Please document it better.
